### ISSUE TITLE
Why is this not in the x86-64 crate

### ISSUE THREAD

**Issue by joskuijpers** [rust-osdev/x86_64_types#1]
Well, the title.

As there is no README either: why is this not inside the x86-64 crate that also supports reading CR registers?

**Comment by phil-opp** [comment]
This is an experiment for moving the type definitions of the `x86_64` crate into a separate crate. The goal is to make them usable when the rest of `x86_64` is not desired.See https://github.com/rust-osdev/x86_64/issues/72 for more information.

**Comment by joskuijpers** [comment]
Ah I see. Thank you.
